### ISSUE TITLE
missing declaration for symbol 'CreateLight'

### ISSUE THREAD

**Issue by coliflor** [TSnake41/raylib-lua#10]
`missing declaration for symbol 'CreateLight'`

The function CreateLight is not present in your package but raylib 4.5-dev contains it.

**Comment by TSnake41** [comment]
CreateLight is actually a part of an example, and not of raylib itself (removed from raylib a long time ago).
https://github.com/raysan5/raylib/blob/master/examples/shaders/rlights.h

It needs an external shader to work, check https://github.com/raysan5/raylib/blob/master/examples/shaders/shaders_basic_lighting.c

**Comment by coliflor** [comment]
true
