### ISSUE TITLE
Part of the `README.md` lists "3.5" as a version, but elsewhere the library is claimed to be "4.5". Which is correct?

### ISSUE THREAD

**Issue by WraithGlade** [TSnake41/raylib-lua#14]
The `README.md` currently has the following in it:

> raylib-lua (raylua) currently uses raylib 3.5 API. 

However, elsewhere on the repository and also on [the big raylib bindings list](https://github.com/raysan5/raylib/blob/master/BINDINGS.md) this library's version is listed as being 4.5.

Is this bindings library still using 3.5 for some parts of its code or has that text simply not been updated yet?

Should that version number be changed to 4.5?

Anyway, thank your for your time and for your work on this bindings library. I look forward to trying it out. 😎

**Comment by TSnake41** [comment]
This statement is outdated (it's now using 4.5).

Fixed in https://github.com/TSnake41/raylib-lua/commit/4da8f4d803ecec6ef9a3b4842dfc9df96467dc5d
