### ISSUE TITLE
Explain the purpose of `raylua_r` in `README.md`

### ISSUE THREAD

**Issue by WraithGlade** [TSnake41/raylib-lua#15]
When I downloaded the compiled binaries for the raylib Lua bindings, I noticed that it had an extra EXE file in the zip file which was not mentioned anywhere on the `README.md` page.

What is it intended for?

I think some comment about what it is should probably be added to the `README.md` to avoid confusion.

**Comment by TSnake41** [comment]
It's a raylua_e variant meant for distribution that is useful for Windows only, it's partially explained [here](https://github.com/TSnake41/raylib-lua/pull/3).

We definitely need some note in README.md to explain what it is.

**Comment by WraithGlade** [comment]
Ok, I submitted the new section as a pull request as requested. I hope you
like it. 🙂

Anyway, have a great day!

**Comment by TSnake41** [comment]
Fixed in #16
