### ISSUE TITLE
Error trying to initialize a window

### ISSUE THREAD

**Issue by 1MarcosDev** [TSnake41/raylib-lua#2]
Hi, first of all, thanks for the amazing work with raylib-lua, this is definitely the best raylib port for lua that I could find, it meets all my requirements. However, I am having a small problem and would like instructions to fix it, as I have no experience with c.

When I run raylua_s, it runs the REPL normally, however, when I try to start a window, with the following code, it returns the following error:

Code:

```
local screenWidth = 800
local screenHeight = 450

rl.InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window")
rl.SetTargetFPS(60)

while not rl.WindowShouldClose() do
  rl.BeginDrawing()
  rl.ClearBackground(rl.RAYWHITE)
  rl.DrawText("Congrats! You created your first window!", 190, 200, 20, rl.LIGHTGRAY)
  rl.DrawFPS(10, 10)
  rl.EndDrawing()
end

rl.CloseWindow()
```

Error:

> $ ./raylua_s main.lua 
> RAYLUA: Raylua boot script
> RAYLUA: Lua Version: Lua 5.1
> RAYLUA: Lua JIT: LuaJIT 2.1.0-beta3
> RAYLUA: Loading FFI binding entries.
> RAYLUA: Loaded 823 FFI entries.
> INFO: Initializing raylib 4.0
> WARNING: GLFW: Error: 65543 Description: GLX: Failed to create context: GLXBadFBConfig
> WARNING: GLFW: Failed to initialize Window
> FATAL: Failed to initialize Graphic Device
> $ 

I researched, and I didn't find any solution regarding raylib.

I would be very grateful if you could help me resolve this error.

Grateful for the answer.

**Comment by TSnake41** [comment]
This is a raylib problem, there is something wrong with your desktop setup.
Please provide more detail on the operating system you use, and the gpu, driver versions, ...

**Comment by 1MarcosDev** [comment]
> This is a raylib problem, there is probably something wrong with your desktop setup.
> Please provide more detail on the operating system you use, and the gpu, driver versions, ...

Lubuntu 20.04
2gb of ram
Intel Celeron, 1.10GHz

All system drives have been updated along with the system. The reason I switched to its latest version was a bug in several programs with GLIBC, which no longer happen with the new version.
