### ISSUE TITLE
Using Vector2 negation causes performance impact

### ISSUE THREAD

**Issue by archaicvirus** [TSnake41/raylib-lua#29]
I'm using DrawTextureRec in a loop to draw a procedural tilemap from a single png image as the texture source. The positions and source rectangles are each in a pre-computed table, however the 'subTile' position must be subtracted from the tile position to draw the tiles in the correct position based on the players position within a tile. This subTile position is calculated once outside the draw loop, and used within the draw loop to offset the pre-computed positions. I'm creating the subtile vector using rl.new("Vector2", x, y), and I notice the slowdown only when subtracting the subtile vector from the pre-computed vector inside of the DrawTectureRec function. If I remove the (position - subtile) and instead just use position, I get 144fps (the target fps in my case). When going back and using (position - subTile) the slowdown comes back, at around 90fps consistently. I looked into the operator overload in compat.lua, and perhaps the if/else statements (to check if params are vector2's) in the __sub metamethod cause this? My game world is 41x26 tiles, which I know is 1,066 total (worst case) plus a background layer, but the issue only occurs when using the negation operator with Vector2's.

Edit:
I tried commenting out the lines in compat.lua - the if/else block I referred to starting at line 50, and just returning the new vector without checking the type. I rebuilt raylua with this change and rebuilt my project, and the slowdown issue persists unfortunately, although now I'm getting about 95 fps versus the previous 90.

**Comment by TSnake41** [comment]
This is probably due to substrat operating building new Vector2 objects, this is needed to not mutate the operands.
If you actually do `position = position - subTile`, you can consider doing `position.x = position x - subTile.x (and same for y)

**Comment by archaicvirus** [comment]
> This is probably due to substract operator building new Vector2 objects, this is needed to not mutate the operands. If you actually do `position = position - subTile`, you can consider doing `position.x = position.x - subTile.x` (and same for y) which doesn't build new objects.

I can confirm this. I just tried creating a temporary 3rd vector2, and using it in the inner loop like this `            temp.x = self.positions[y][x].x - subtile.x
            temp.y = self.positions[y][x].y - subtile.y`
